clean-blog/config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  root 'clean_blogs#index'
  get  'about' 	=> 'clean_blogs#about'
  get  'post' 	=> 'clean_blogs#post'
  resources :users
  resources :articles do
    resources :comments
  end
end

clean-blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

clean-blog/app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
    validates :user_id, presence: true
    belongs_to :user
    belongs_to :category
    has_many :comments
end

clean-blog/app/models/category.rb
class Category < ApplicationRecord
    has_many :articles
end

clean-blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

clean-blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :articles
end

clean-blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!, only: [:create, :destroy, :edit]
     protect_from_forgery with: :exception
     helper_method :current_user, :logged_in?
end

clean-blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def index
        if params[:category].blank?
            @articles = Article.all.order("created_at ASC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @articles = Article.where(category_id: @category_id).order("created_at DESC")
        end
    end

    def new
        @article = current_user.articles.new
        @categories = Category.new
    end

    def create
        @article = current_user.articles.new(article_params)
        if @article.save
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
        @comment = Comment.new
    end

    def edit
    end

    def update
        if @article.update(article_params)
         flash[:success] = "article was updated"
         redirect_to article_path(@article)
        else
         flash[:success] = "article was not updated"
         render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:success] = "article was deleted"
        redirect_to root_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :description, :category_id)
        end

        def set_article
            @article = Article.find(params[:id])
        end
end

clean-blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

clean-blog/app/controllers/clean_blogs_controller.rb
class CleanBlogsController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
	layout "clean_blog"
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.find(current_user.id)
        if @article.save
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @article.update(article_params)
         flash[:success] = "article was updated"
         redirect_to article_path(@article)
        else
         flash[:success] = "article was not updated"
         render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:success] = "article was deleted"
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :description)
        end

        def set_article
            @article = Article.find(params[:id])
        end
end

clean-blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_article
    def create
        @comment = Comment.new(comment_params)
        @comment.author_name = current_user.email.split('@').first
        @comment.article_id = params[:article_id]
        @comment.save
        redirect_to article_path(@comment.article)
    end

    def destroy
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@comment.article)
    end
      
    def comment_params
        params.require(:comment).permit(:body)
    end

    private 
        def set_article
            @article = Article.find params[:article_id]
        end

end

clean-blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index

    end
    
    def about

    end
end

clean-blog/app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     size = options[:size]
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

clean-blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

clean-blog/app/helpers/clean_blogs_helper.rb
module CleanBlogsHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
      base_title = "Clean Blog"
      if page_title.empty?
          base_title
      else
          "#{base_title} - #{page_title}"
      end
  end
end

clean-blog/app/helpers/comments_helper.rb
module CommentsHelper
end

clean-blog/app/views/articles/_comment.html.erb
<div class="comment-form">
    <form>
    <h4>comment by <%= comment.author_name %></h4>
    <hr>
    <h4 class="comment"><%= comment.body %></h4>
    <%= link_to "delete", article_comment_path(@article, comment), method: :delete %>
    </form>
</div>

clean-blog/app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="create">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><a>title</a></span>
            <%= f.text_field :title, class: "form-control", autofocus: true %><br>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><a>text</a></span>
            <%= f.text_area :description, rows: 10, class: "form-control"%>
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><a>cat</a></span>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {prompt: "choose a category" }, {:class => 'form-control'})%>
        </div>
    </div>
    <div class="form-group">
        <%=f.submit("post", {:class=>'btn btn-lg btn-primary btn-block'})%>
    </div>
    </form>
    <% end %>
</div>

clean-blog/app/views/articles/edit.html.erb
<%= render 'form' %>

clean-blog/app/views/articles/index.html.erb
<br><br><br><br><br>
<% @articles.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 500) %>
            </div>
            <div class="article-meta-details">
                <small>created by: <%= article.user.email.split('@').first%>,
                    <%= time_ago_in_words(article.created_at) %> ago, last updated:
                    <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
            <div class="article-actions">
                <%= link_to "edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "delete", article_path(article), method: :delete, data: { confirm: "are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

clean-blog/app/views/articles/new.html.erb
<%= render 'form' %>

clean-blog/app/views/articles/show.html.erb
<%= render 'clean_blogs/shim' %>
<%= render 'clean_blogs/navigation' %>
<%= render 'clean_blogs/header' %>

<!-- Post Content -->
<article>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p><%= simple_format(@article.description) %></p><br>
            </div>
        </div>
    </div>
</article>

<br>
<center>
    <%= render partial: 'comments/form' %>
    <%= render partial: 'articles/comment', collection: @article.comments.reverse %>
    <%= link_to "edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
    <%= link_to "delete", article_path(@article), method: :delete, data: { confirm: "are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    |
    <%= link_to 'back', articles_path, class: "btn btn-xs btn-success" %>
</center>
<%= render 'clean_blogs/footer' %>

clean-blog/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

clean-blog/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

clean-blog/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

clean-blog/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

clean-blog/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

clean-blog/app/views/clean_blogs/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg" style="font-size: 20px;">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse" style="background-color:#8F125F;"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg" style="font-size: 20px;">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse" style="background-color:#8F125F;"></i>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

clean-blog/app/views/clean_blogs/_header.html.erb
<% if current_page?(root_path) %>
    <header class="intro-header">
    <div class="background-image">
        <div class="oesia"><img src="/assets/clean_blog/oesia.png" height="80" width="140"></div>
        <div class="tecnobit"><img src="/assets/clean_blog/tecnobit.png" height="90" width="250"></div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="site-heading">
                    <h1>tbitblog</h1>
                    <hr class="small">
                    <span class="subheading">rails+bootstrap dev test blog theme</span>
                </div>
            </div>
        </div>
    </div>
    </header>
<% elsif current_page?(article_path) %>
    <header class="intro-header">
        <div class="background-image">
            <div class="oesia"><img src="/assets/clean_blog/oesia.png" height="80" width="140"></div>
            <div class="tecnobit"><img src="/assets/clean_blog/tecnobit.png" height="90" width="250"></div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <center><h1><%= @article.title %></h1></center>
                        <center><span class="meta">posted by <a><%= link_to @article.user.email.split('@').first, edit_user_registration_path%></a> on <%= @article.created_at.strftime("%B %d %Y") %></span></center>
                    </div>
                </div>
            </div>
        </div>
    </header>
<% end %>

clean-blog/app/views/clean_blogs/_navigation.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" <%= link_to "tbitblog", root_path %></a> </div> <!-- Collect the nav links, forms,
                and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <%= link_to "home", root_path %>
                        </li>
                        <% Category.all.each do |category| %>
                        <li>
                            <%= link_to category.name, articles_path(category: category.name) %>
                        </li>
                        <% end %>
                        <li><%= link_to "create article", new_article_path %></li>
                        <% if user_signed_in? %>
                        <li><%= link_to 'logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                        </li>
                        <li>
                            <%= link_to current_user.email.split('@').first, edit_user_registration_path, :class => 'navbar-link'  %>
                        </li>
                        <% else %>
                        <li><%= link_to "login", new_user_session_path, :class => 'navbar-link'  %></li>
                        <li><%= link_to "sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                        <% end %>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
</nav>

clean-blog/app/views/clean_blogs/_shim.html.erb
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

clean-blog/app/views/clean_blogs/index.html.erb
<title>tbitblog</title>

<%= render 'shim' %>
<%= render 'navigation' %>
<%= render 'header' %>
<% @articles.reverse.each do |article| %>

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-preview">
                <%= link_to article_path(article) do %>
                    <h1 class="post-title">
                        <%= article.title %>
                    </h1>
                    <h3 class="post-subtitle">
                        <%= truncate(article.description, length: 64, omission: '... (read more)') %>
                    </h3>
                <% end %>
                <p class="post-meta">posted by <a><%= link_to article.user.email.split('@').first, edit_user_registration_path%></a> on <%= article.created_at.strftime("%B %d %Y")%></p>
                <%= link_to "edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
            <hr>
        </div>
    </div>
</div>

<br>
<% end %>
<%= render 'footer' %>

clean-blog/app/views/comments/_form.html.erb
<div class="comment-form">
<%= form_for [@article, @comment] do |f| %>
<h3><%= @article.comments.size %> comments</h3>
<h2>post a comment</h2>
<hr>
    <div class="form-group">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-comment"></i></span>
            <%= f.text_area :body, autofocus: true, rows: 4, class: 'form-control' %>
        </div>
    </div>
    <div class="form-group">
        <%=f.submit("comment", {:class=>'btn btn-lg btn-primary btn-block'})%>
    </div>
    </form>
    <% end %>
  </div>

clean-blog/app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "blog", root_path, class: "navbar-brand", id: "logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "create article", new_article_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <p class="navbar-text pull-right">
                    <% if user_signed_in? %>
                    logged in as <strong><%= current_user.email %></strong>
                    <li><%= link_to 'logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li> 
                    <li> <%= link_to 'edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                    <% else %>
                    <li><%= link_to "login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <li><%= link_to "sign up", new_user_registration_path, :class => 'navbar-link'  %></li>  
                    <% end %>
                </p>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

clean-blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>tbitblog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <%= render 'clean_blogs/navigation' %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</body>

</html>

clean-blog/app/views/layouts/clean_blog.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>tbitblog</title>
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link
    href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
    rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
</head>

<body>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

</body>
</html>

clean-blog/app/views/shared/_article.html.erb
<% obj.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
                <div class="article-meta-details">
                    <small>Created by: <%= article.user.username if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
            </div>
            <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

clean-blog/app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(obj.errors.count, "error") %>
                    prohibited this object from being saved:
                </h2>
                <div class="panel-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg|%>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

clean-blog/app/views/shared/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
</div>