config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'
  get 'about', to: 'pages#about'
  resources :articles #scaffold to create predefined stuff
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
    validates :user_id, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     before_action :authenticate_user!, only: [:create, :destroy, :edit]
     protect_from_forgery with: :exception
     helper_method :current_user, :logged_in?
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :update, :show, :destroy]
    def index
        @articles = Article.all
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.find(current_user.id)
        if @article.save
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        if @article.update(article_params)
         flash[:success] = "article was updated"
         redirect_to article_path(@article)
        else
         flash[:success] = "article was not updated"
         render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:success] = "article was deleted"
        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :description)
        end

        def set_article
            @article = Article.find(params[:id])
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index

    end
    
    def about

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
     gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
     size = options[:size]
     gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
     image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="create">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><a>title</a></span>
                <%= f.text_field :title, class: "form-control", autofocus: true %><br>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <span class="input-group-addon"><a>text</a></span>
                <%= f.text_area :description, rows: 10, class: "form-control"%>
            </div>
        </div>
        <div class="form-group">
            <%=f.submit("post", {:class=>'btn btn-lg btn-primary btn-block'})%>
        </div>
        </form>
        <% end %>
    </div>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<br>
<% @articles.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 500) %>
            </div>
            <div class="article-meta-details">
                <small>created by: <%= article.user.email.split('@').first%>,
                    <%= time_ago_in_words(article.created_at) %> ago, last updated:
                    <%= time_ago_in_words(article.updated_at) %> ago</small>
            </div>
            <div class="article-actions">
                <%= link_to "edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
    <%= simple_format(@article.description) %>
    <%= link_to "edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %> |
    <%= link_to "delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %> |
    <%= link_to 'back', articles_path, class: "btn btn-xs btn-success" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "blog", root_path, class: "navbar-brand", id: "logo" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to "create article", new_article_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <p class="navbar-text pull-right">
                    <% if user_signed_in? %>
                    logged in as <strong><%= current_user.email %></strong>
                    <li><%= link_to 'logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li> 
                    <li> <%= link_to 'edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                    
                    <% else %>
                    <li><%= link_to "login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <li><%= link_to "sign up", new_user_registration_path, :class => 'navbar-link'  %></li>  
                    <% end %>
                </p>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>blog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <%= render 'layouts/navigation' %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<h1>acerca del blog</h1>
<%= link_to 'home', root_path %>

app/views/pages/index.html.erb
<h1>bienvenido al blog</h1>
<%= link_to 'about', about_path %>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
                <div class="article-meta-details">
                    <small>Created by: <%= article.user.username if article.user %>,
                        <%= time_ago_in_words(article.created_at) %> ago,
                        last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
            </div>
            <div class="article-actions">
                <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(obj.errors.count, "error") %>
                    prohibited this object from being saved:
                </h2>
                <div class="panel-body">
                    <ul>
                        <% obj.errors.full_messages.each do |msg|%>
                        <li><%= msg %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        <% flash.each do |name, msg| %>
        <div class='alert alert-<%= "#{name}" %>'>
            <a href="#" class="close" data-dismiss="alert">&#215;</a>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        </div>
        <% end %>
    </div>
</div>